import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { WagmiConfig, createClient, chain } from "wagmi";
import { ConnectKitProvider, getDefaultClient } from "connectkit";
import Navbar from '../components/nav/Navbar'

const alchemyId = process.env.ALCHEMY_ID;

// Choose which chains you'd like to show
const chains = [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum, chain.goerli];

const client = createClient(
  getDefaultClient({
    appName: 'Nift NFT Marketplace',
    alchemyId,
    chains,
  }),
);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div> 
      <WagmiConfig client={client}>
      <ConnectKitProvider theme="auto" mode="light" customTheme={{
      "--ck-connectbutton-background": "linear-gradient(95.49deg, #FCAD02 -36.87%, #FF0041 98.63%);",
      "--ck-connectbutton-color": "#fff",
      "--ck-connectbutton-hover-background": "#FCAD02",
      "--ck-connectbutton-hover-color": "#fff",
      "--ck-connectbutton-font-size": "17px",
    }}
    >
    <Head>
        <title>Nift NFT MarketPlace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
        integrity='sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc'
        crossOrigin='anonymous' />
      </Head>
       <Navbar />
      <Component {...pageProps} />
      </ConnectKitProvider>
    </WagmiConfig>
   </div>
  )
}

export default MyApp
